In [1]:
import numpy as np

In [38]:
class Node():
    def __init__(self, state, parent, move, cost): 

        self.state = state
        #self.goal = goal_state
        self.parent = parent
        self.move = move
        self.cost = cost
        
    def getState(self):
        return self.state
		
    def getParent(self):
        return self.parent
		
    def getMove(self):
	    return self.move
		
    def getCost(self):
        return self.cost

    def getFullPath(self):
        
        moves = []
        current_node = self
        while(current_node.getMove() is not None):

            moves.append(current_node.getMove())
            print(current_node.getMove())
            current_node = current_node.getParent()

        moves.reverse()
        return moves



In [3]:
def getBranches(node):

    moves = ["up", "down", "left", "right"]
    branches = []
    branches.append(Node(moveUp(node.getState()), node, moves[0], node.getCost() + 1))
    branches.append(Node(moveDown(node.getState()), node, moves[1], node.getCost() + 1))
    branches.append(Node(moveRight(node.getState()), node, moves[2], node.getCost() + 1))
    branches.append(Node(moveLeft(node.getState()), node, moves[3], node.getCost() + 1))

    #remove None nodes
    b = [branch for branch in branches if branch.getState() is not None]
            
    return b



In [4]:
def moveUp(state):

    state_copy = state.copy()
    position = np.where(state_copy == 0)
    position = int(position[0])

    num_cols = 3
 
    if position not in [0, 1, 2]:
        #can move up
        #swap with the upper row
        tmp = state[position]
        state_copy[position] = state_copy[position - num_cols]
        state_copy[position - num_cols] = tmp
        return state_copy
    else:
        return None

def moveDown(state):
    state_copy = state.copy()
    position = np.where(state_copy == 0)
    position = int(position[0])

    num_cols = 3
    
    if position not in [6, 7, 8]:
        #can move down
        #swap with the lower row
        tmp = state[position]
        state_copy[position] = state_copy[position + num_cols]
        state_copy[position + num_cols] = tmp
        return state_copy
    else:
        return None

def moveRight(state):
    state_copy = state.copy()
    position = np.where(state_copy == 0)
    position = int(position[0])

    if position not in [2, 5, 8]:
        #can move right
        #swap with the reft col
        tmp = state_copy[position]
        state_copy[position] = state_copy[position + 1]
        state_copy[position + 1] = tmp
        return state_copy
    else:
        return None

def moveLeft(state):
    state_copy = state.copy()
    position = np.where(state_copy == 0)
    position = int(position[0])
    #num_rows = 3 
    if position not in [0, 3, 6]:
        #can move left
        #swap with the left col
        tmp = state_copy[position]
        state_copy[position] = state_copy[position - 1]
        state_copy[position - 1] = tmp
        return state_copy
    else:
        return None

In [25]:
def bfsSearch(init_state, goal_state):

    nodes = list()
    visited_states = list()

    init_node = Node(init_state, 0, None, 0)
    nodes.append(init_node)

    while(True):

        current_node = nodes.pop()
        visited_states.append(current_node.getState())

        if np.all(current_node.state == goal_state):
            print("Goal Reached!")
            full_path = current_node.getFullPath()
            return full_path

        else:

            branches = getBranches(current_node)
            for branch in branches:
                print(branch.getState())
    

            for branch in branches:
                branch_state = branch.getState()
                
                for visited_state in visited_states:
                    if not np.all(branch_state == visited_state):
                        nodes.insert(0, branch)

In [42]:
def main():
    #get inital state
    initial_state = np.array([1, 4, 2, 3, 0, 5, 6, 7, 8])
    #get goal state
    goal_state = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
    print("initial state is: ", initial_state)
    print("goal state is: ", initial_state)
    path = bfsSearch(initial_state, goal_state)
    print(path)


In [43]:
if __name__ == "__main__":
    main()

initial state is:  [1 4 2 3 0 5 6 7 8]
goal state is:  [1 4 2 3 0 5 6 7 8]
[1 0 2 3 4 5 6 7 8]
[1 4 2 3 7 5 6 0 8]
[1 4 2 3 5 0 6 7 8]
[1 4 2 0 3 5 6 7 8]
[1 4 2 3 0 5 6 7 8]
[1 2 0 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[1 4 2 3 0 5 6 7 8]
[1 4 2 3 7 5 6 8 0]
[1 4 2 3 7 5 0 6 8]
[1 4 0 3 5 2 6 7 8]
[1 4 2 3 5 8 6 7 0]
[1 4 2 3 0 5 6 7 8]
[0 4 2 1 3 5 6 7 8]
[1 4 2 6 3 5 0 7 8]
[1 4 2 3 0 5 6 7 8]
[1 0 2 3 4 5 6 7 8]
[1 4 2 3 7 5 6 0 8]
[1 4 2 3 5 0 6 7 8]
[1 4 2 0 3 5 6 7 8]
[1 2 5 3 4 0 6 7 8]
[1 0 2 3 4 5 6 7 8]
[1 2 5 3 4 0 6 7 8]
[1 0 2 3 4 5 6 7 8]
Goal Reached!
right
up
['up', 'right']


In [40]:
#get inital state
initial_state = np.array([1, 0, 2, 3, 4, 5, 6, 7, 8])
#get goal state
goal_state = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print("initial state is: ", initial_state)
print("goal state is: ", goal_state)
path = bfsSearch(initial_state, goal_state)
print(path)

initial state is:  [1 0 2 3 4 5 6 7 8]
goal state is:  [0 1 2 3 4 5 6 7 8]
[1 4 2 3 0 5 6 7 8]
[1 2 0 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[1 0 2 3 4 5 6 7 8]
[1 4 2 3 7 5 6 0 8]
[1 4 2 3 5 0 6 7 8]
[1 4 2 0 3 5 6 7 8]
[1 2 5 3 4 0 6 7 8]
[1 0 2 3 4 5 6 7 8]
Goal Reached!
right
['right']


In [36]:
type(goal_state)

numpy.ndarray

In [4]:
visited_states = list()

In [4]:
visited_states.append(initial_state)
visited_states.append(initial_state)

In [23]:
if np.any(visited_state in visited_states):
    print("yes")
else:
    print("no")

SyntaxError: invalid syntax (<ipython-input-23-239810a5870e>, line 1)

In [16]:
visited_states.index(initial_state)

0

In [5]:
init_node = Node(initial_state, None, None, 0)

In [7]:
visited_states.append(init_node.getState())

In [14]:
if visited_states in visited_states:
    print("yes")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [12]:
visited_states

[array([1, 0, 2, 3, 4, 5, 6, 7, 8]), array([1, 0, 2, 3, 4, 5, 6, 7, 8])]

In [13]:
init_node.getState()

array([1, 0, 2, 3, 4, 5, 6, 7, 8])

In [15]:
visited_states in visited_states

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()